pipeline:
  - name: "nlp_spacy"
  - name: tokenizer_spacy
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
  - name: ner_synonyms
  - name: intent_featurizer_count_vectors
    token_pattern: (?u)\b\w+\b
  - name: intent_classifier_tensorflow_embedding
    dimensions:
    - number
language: en_core_web_sm